// Generated by scripts/db/generate-pg-schema.ts from schema.sqlite.ts; do not edit.
// Change schema.sqlite.ts and run `bun run db:generate-pg-schema`.
/**
 * The tables the application queries (`@/src/lib/db/schema`). They are
 * authored in schema.sqlite.ts; schema.pg.ts holds the same tables for
 * PostgreSQL. Every table is exported typed as its SQLite table, so a query
 * type-checks the same way on either dialect.
 * The dialect's tables are chosen once, at module load.
 */
import { getDialect } from "./dialect";
import * as pgSchema from "./schema.pg";
import * as sqliteSchema from "./schema.sqlite";

const tables = (getDialect() === "postgres" ? pgSchema : sqliteSchema) as unknown as typeof sqliteSchema;

export const users = tables.users;
export const signInSources = tables.signInSources;
export const sessions = tables.sessions;
export const accounts = tables.accounts;
export const verifications = tables.verifications;
export const oauthProviders = tables.oauthProviders;
export const oauthStates = tables.oauthStates;
export const pendingOAuthLinks = tables.pendingOAuthLinks;
export const settings = tables.settings;
export const instances = tables.instances;
export const accessLists = tables.accessLists;
export const accessListEntries = tables.accessListEntries;
export const certificates = tables.certificates;
export const caCertificates = tables.caCertificates;
export const issuedClientCertificates = tables.issuedClientCertificates;
export const proxyHosts = tables.proxyHosts;
export const apiTokens = tables.apiTokens;
export const auditEvents = tables.auditEvents;
export const linkingTokens = tables.linkingTokens;
export const logParseState = tables.logParseState;
export const wafLogParseState = tables.wafLogParseState;
export const mtlsRoles = tables.mtlsRoles;
export const mtlsCertificateRoles = tables.mtlsCertificateRoles;
export const mtlsAccessRules = tables.mtlsAccessRules;
export const groups = tables.groups;
export const groupMembers = tables.groupMembers;
export const forwardAuthAccess = tables.forwardAuthAccess;
export const forwardAuthSessions = tables.forwardAuthSessions;
export const forwardAuthExchanges = tables.forwardAuthExchanges;
export const forwardAuthRedirectIntents = tables.forwardAuthRedirectIntents;
export const l4ProxyHosts = tables.l4ProxyHosts;
export const auditSinks = tables.auditSinks;
export const configSnapshots = tables.configSnapshots;
export const alertChannels = tables.alertChannels;
export const alertRules = tables.alertRules;
export const alertRuleStates = tables.alertRuleStates;
export const alertEvents = tables.alertEvents;
export const alertSilences = tables.alertSilences;
export const backupDestinations = tables.backupDestinations;
export const backupRuns = tables.backupRuns;
export const wafTuningSuggestions = tables.wafTuningSuggestions;
export const twoFactors = tables.twoFactors;
export const customRoles = tables.customRoles;
export const monetizationPlans = tables.monetizationPlans;
export const monetizationConsumers = tables.monetizationConsumers;
export const monetizationKeys = tables.monetizationKeys;
export const monetizationLedger = tables.monetizationLedger;
export const monetizationHosts = tables.monetizationHosts;
export const approvalPolicies = tables.approvalPolicies;
export const complianceReports = tables.complianceReports;
export const changeRequests = tables.changeRequests;
export const changeRequestReviews = tables.changeRequestReviews;
export const complianceIncidents = tables.complianceIncidents;
export const ldapDirectories = tables.ldapDirectories;
export const scimTokens = tables.scimTokens;
export const scimUsers = tables.scimUsers;
export const scimGroups = tables.scimGroups;
export const scimGroupMembers = tables.scimGroupMembers;
export const scimRoleMappings = tables.scimRoleMappings;
export const accessReviewCampaigns = tables.accessReviewCampaigns;
export const accessReviewItems = tables.accessReviewItems;
export const accessReviewSchedules = tables.accessReviewSchedules;
export const fleetEnvironments = tables.fleetEnvironments;
export const fleetInstances = tables.fleetInstances;
export const fleetRevisions = tables.fleetRevisions;
export const fleetRollouts = tables.fleetRollouts;
export const fleetRolloutTargets = tables.fleetRolloutTargets;
export const fleetPullReplicas = tables.fleetPullReplicas;
export const samlProviders = tables.samlProviders;
export const samlGroupRoles = tables.samlGroupRoles;
export const samlRequests = tables.samlRequests;
export const samlUsedAssertions = tables.samlUsedAssertions;
export const analyticsSavedViews = tables.analyticsSavedViews;
export const wafRuleExclusions = tables.wafRuleExclusions;
export const accessListRules = tables.accessListRules;
export const passkeys = tables.passkeys;
export const userPreferences = tables.userPreferences;
export const ldapDirectoryHealth = tables.ldapDirectoryHealth;
export const complianceReportSchedules = tables.complianceReportSchedules;
export const complianceRestoreTests = tables.complianceRestoreTests;
export const analyticsQuestions = tables.analyticsQuestions;
export const monetizationSharedCursors = tables.monetizationSharedCursors;
export const monetizationSharedCredits = tables.monetizationSharedCredits;
export const clusterNodes = tables.clusterNodes;
export const rateLimitCounters = tables.rateLimitCounters;
export const authRateLimits = tables.authRateLimits;
export const sharedRuntimeEntries = tables.sharedRuntimeEntries;
export const monetizationPayments = tables.monetizationPayments;
export const monetizationAnswerCredits = tables.monetizationAnswerCredits;
export const monetizationX402Payments = tables.monetizationX402Payments;
