-- Items of "Needs attention" an account hid from its own overview
-- (drizzle/0062_attention_dismissals.sql has the same change for SQLite).
CREATE TABLE "attention_dismissals" (
	"id" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "attention_dismissals_id_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1),
	"userId" integer NOT NULL,
	"source" text NOT NULL,
	"itemId" text NOT NULL,
	"severity" text NOT NULL,
	"until" text NOT NULL,
	"createdAt" text NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX "attention_dismissals_item_unique" ON "attention_dismissals" USING btree ("userId","source","itemId");
